/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTrainingsRouteImport } from './routes/dashboard/trainings'
import { Route as DashboardStudentsRouteImport } from './routes/dashboard/students'
import { Route as DashboardResourcesRouteImport } from './routes/dashboard/resources'
import { Route as DashboardMyEnrollmentRouteImport } from './routes/dashboard/my-enrollment'
import { Route as DashboardMyClassRouteImport } from './routes/dashboard/my-class'
import { Route as DashboardEnrollmentsRouteImport } from './routes/dashboard/enrollments'
import { Route as DashboardClassRouteImport } from './routes/dashboard/class'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTrainingsRoute = DashboardTrainingsRouteImport.update({
  id: '/trainings',
  path: '/trainings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudentsRoute = DashboardStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResourcesRoute = DashboardResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMyEnrollmentRoute = DashboardMyEnrollmentRouteImport.update({
  id: '/my-enrollment',
  path: '/my-enrollment',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMyClassRoute = DashboardMyClassRouteImport.update({
  id: '/my-class',
  path: '/my-class',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEnrollmentsRoute = DashboardEnrollmentsRouteImport.update({
  id: '/enrollments',
  path: '/enrollments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClassRoute = DashboardClassRouteImport.update({
  id: '/class',
  path: '/class',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/class': typeof DashboardClassRoute
  '/dashboard/enrollments': typeof DashboardEnrollmentsRoute
  '/dashboard/my-class': typeof DashboardMyClassRoute
  '/dashboard/my-enrollment': typeof DashboardMyEnrollmentRoute
  '/dashboard/resources': typeof DashboardResourcesRoute
  '/dashboard/students': typeof DashboardStudentsRoute
  '/dashboard/trainings': typeof DashboardTrainingsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/class': typeof DashboardClassRoute
  '/dashboard/enrollments': typeof DashboardEnrollmentsRoute
  '/dashboard/my-class': typeof DashboardMyClassRoute
  '/dashboard/my-enrollment': typeof DashboardMyEnrollmentRoute
  '/dashboard/resources': typeof DashboardResourcesRoute
  '/dashboard/students': typeof DashboardStudentsRoute
  '/dashboard/trainings': typeof DashboardTrainingsRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/class': typeof DashboardClassRoute
  '/dashboard/enrollments': typeof DashboardEnrollmentsRoute
  '/dashboard/my-class': typeof DashboardMyClassRoute
  '/dashboard/my-enrollment': typeof DashboardMyEnrollmentRoute
  '/dashboard/resources': typeof DashboardResourcesRoute
  '/dashboard/students': typeof DashboardStudentsRoute
  '/dashboard/trainings': typeof DashboardTrainingsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/class'
    | '/dashboard/enrollments'
    | '/dashboard/my-class'
    | '/dashboard/my-enrollment'
    | '/dashboard/resources'
    | '/dashboard/students'
    | '/dashboard/trainings'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard/class'
    | '/dashboard/enrollments'
    | '/dashboard/my-class'
    | '/dashboard/my-enrollment'
    | '/dashboard/resources'
    | '/dashboard/students'
    | '/dashboard/trainings'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/class'
    | '/dashboard/enrollments'
    | '/dashboard/my-class'
    | '/dashboard/my-enrollment'
    | '/dashboard/resources'
    | '/dashboard/students'
    | '/dashboard/trainings'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/trainings': {
      id: '/dashboard/trainings'
      path: '/trainings'
      fullPath: '/dashboard/trainings'
      preLoaderRoute: typeof DashboardTrainingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/students': {
      id: '/dashboard/students'
      path: '/students'
      fullPath: '/dashboard/students'
      preLoaderRoute: typeof DashboardStudentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/resources': {
      id: '/dashboard/resources'
      path: '/resources'
      fullPath: '/dashboard/resources'
      preLoaderRoute: typeof DashboardResourcesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/my-enrollment': {
      id: '/dashboard/my-enrollment'
      path: '/my-enrollment'
      fullPath: '/dashboard/my-enrollment'
      preLoaderRoute: typeof DashboardMyEnrollmentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/my-class': {
      id: '/dashboard/my-class'
      path: '/my-class'
      fullPath: '/dashboard/my-class'
      preLoaderRoute: typeof DashboardMyClassRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/enrollments': {
      id: '/dashboard/enrollments'
      path: '/enrollments'
      fullPath: '/dashboard/enrollments'
      preLoaderRoute: typeof DashboardEnrollmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/class': {
      id: '/dashboard/class'
      path: '/class'
      fullPath: '/dashboard/class'
      preLoaderRoute: typeof DashboardClassRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardClassRoute: typeof DashboardClassRoute
  DashboardEnrollmentsRoute: typeof DashboardEnrollmentsRoute
  DashboardMyClassRoute: typeof DashboardMyClassRoute
  DashboardMyEnrollmentRoute: typeof DashboardMyEnrollmentRoute
  DashboardResourcesRoute: typeof DashboardResourcesRoute
  DashboardStudentsRoute: typeof DashboardStudentsRoute
  DashboardTrainingsRoute: typeof DashboardTrainingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardClassRoute: DashboardClassRoute,
  DashboardEnrollmentsRoute: DashboardEnrollmentsRoute,
  DashboardMyClassRoute: DashboardMyClassRoute,
  DashboardMyEnrollmentRoute: DashboardMyEnrollmentRoute,
  DashboardResourcesRoute: DashboardResourcesRoute,
  DashboardStudentsRoute: DashboardStudentsRoute,
  DashboardTrainingsRoute: DashboardTrainingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
